name: CTAdvancement
version: ${version}
main: kr.apo2073.ctadvancement.CTA
api-version: '1.20'
authors: [APO2073]
commands:
  cta:
    description: CTAdvancement command

permissions:
  apo.cta.*:
    children:
      apo.cta.reload:
        default: op
      apo.cta.load:
        default: op
      apo.cta.remove:
        default: op
      apo.cta.show:
        default: op

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.10