name: CTAdvancement
version: '1.0'
main: kr.apo2073.customToasts.CustomToasts
api-version: '1.20'
authors: [ 아포칼립스 ]
commands:
  toast:
  reloadToasts:
    description: 커스텀 도전과제 리로드 명령어

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.10