name: CTAdvancement
version: ${version}
main: kr.apo2073.ctadvancement.CTA
api-version: '1.20'
authors: [ 아포칼립스 ]
commands:
  cta:
    description: CTAdvancement 기본 명령어

permissions:
  apo.cta.*:
    children:
      apo.cta.reload:
        default: op
      apo.cta.load:
        default: op
      apo.cta.remove:
        default: op

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.10